server {
    listen 80 default_server;
    listen [::]:80;

    server_name _;

    return 404;
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    
    server_name _;

    ssl_certificate /etc/nginx/ssl/default.crt;
    ssl_certificate_key /etc/nginx/ssl/default.key;

    return 404;
}