# Server default para requisições sem server_name válido
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    access_log /var/log/nginx/invalid-access.log main;
    error_log /var/log/nginx/invalid-error.log warn;

    return 444;
}