name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy
        run: |
          cd /srv/workspace

          git fetch origin
          git reset --hard origin/main

          docker compose down
          docker compose up -d --build